version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Web Console Port
    volumes:
      - ./minio_data:/data # Persists data on your local machine
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio # Make sure MinIO starts first
    env_file:
      - .env

  worker:
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
    depends_on:
      - redis
      - minio # Make sure MinIO starts first
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
